### ISSUE TITLE
Textbox loses its focus when form background is clicked.

### ISSUE THREAD

**Issue by beru** [beru/nana#5]
It is just different from normal windows apps.

**Comment by cnjinhao** [comment]
Hi beru, this feature is implemented in develop branch.

**Comment by beru** [comment]
Wow really? That sounds great! Jinhao I'll check it out.
Considering the same thing happens on web browsers, I'm beginning to think this is a subtle issue.
But the users of desktop applications may benefit from the change.

**Comment by beru** [comment]
I've tested with the develop branch.
Now, it reacts alright with single click but still double clicking form's background can kill the focus.

**Comment by cnjinhao** [comment]
I will fix it, thanks for your feedback.

**Comment by cnjinhao** [comment]
Double click issue is fixed

**Comment by beru** [comment]
Thank you for the fix!
